import type { ProjectInput } from "./types";

export const sampleProject: ProjectInput = {
  projectName: "Timber Wall Panel V1 Example",
  reportingAreaM2: 120,
  giaDemolishedM2: 0,
  referenceStudyPeriodYears: 50,
 assumptions: [
  "Sample factors are placeholders for development only.",
  "A1-A3 finished product includes purchased products, inbound transport, allocated factory manufacturing, and factory waste end processing.",
  "A4 is calculated from delivered-to-site mass, project A4 distance, a 1.43 distance multiplier, and an emission factor of 0.1211 kgCO2e/tkm-equivalent basis used in this prototype.",
  "A5 fossil is calculated as (17.5 × GIA demolished) + (20 × reporting area) + 1% of total A1-A4.",
  "Stored biogenic carbon is tracked separately at material and project level. A5 biogenic release is calculated from stored biogenic carbon and site waste rate.",
  "Net stored biogenic carbon after A5 is reported separately from the main embodied total.",
  "Upfront carbon is reported as A1-A5.",
  "Embodied carbon total is reported as A1-A5 + C1-C4.",
],

  materials: [
    {
      id: "clt",
      name: "CLT panel core",
      boqQty: 120,
      conversionMode: "manual",
      boqUnit: "m2",
      conversionFactorToDeclaredUnit: 0.0,
      thicknessM: 0.12,
      declaredUnit: "m3",
      densityKgPerM3: 470,
      factoryWasteRate: 0.05,
      siteWasteRate: 0.02,
      epdA1A3KgCO2ePerDeclaredUnit: 110,
      massTonnesPerDeclaredUnit: 0.0,
      inboundDistanceKm: 180,
      inboundTransportKgCO2ePerTkm: 0.09,
      factoryWasteTransportDistanceKm: 40,
      factoryWasteTransportKgCO2ePerTkm: 0.09,
      factoryWasteTreatmentKgCO2ePerDeclaredUnit: 2.5,
      siteWasteTransportDistanceKm: 35,
      siteWasteTransportKgCO2ePerTkm: 0.09,
      siteWasteTreatmentKgCO2ePerDeclaredUnit: 3.0,
    },
    {
      id: "insulation",
      name: "Mineral wool insulation",
      boqQty: 120,
      conversionMode: "manual",
      boqUnit: "m2",
      conversionFactorToDeclaredUnit: 0.0,
      thicknessM: 0.14,
      declaredUnit: "m3",
      densityKgPerM3: 40,
      factoryWasteRate: 0.04,
      siteWasteRate: 0.03,
      epdA1A3KgCO2ePerDeclaredUnit: 55,
      massTonnesPerDeclaredUnit: 0.0,
      inboundDistanceKm: 220,
      inboundTransportKgCO2ePerTkm: 0.09,
      factoryWasteTransportDistanceKm: 30,
      factoryWasteTransportKgCO2ePerTkm: 0.09,
      factoryWasteTreatmentKgCO2ePerDeclaredUnit: 1.5,
      siteWasteTransportDistanceKm: 35,
      siteWasteTransportKgCO2ePerTkm: 0.09,
      siteWasteTreatmentKgCO2ePerDeclaredUnit: 2.0,
    },
    {
      id: "plasterboard",
      name: "Plasterboard lining",
      boqQty: 240,
      boqUnit: "m2",
      conversionMode: "manual",
      conversionFactorToDeclaredUnit: 0.0,
      declaredUnit: "m2",
      factoryWasteRate: 0.06,
      surfaceMassKgPerM2: 9.7,
      siteWasteRate: 0.04,
      epdA1A3KgCO2ePerDeclaredUnit: 6.8,
      massTonnesPerDeclaredUnit: 0.0,
      inboundDistanceKm: 140,
      inboundTransportKgCO2ePerTkm: 0.09,
      factoryWasteTransportDistanceKm: 25,
      factoryWasteTransportKgCO2ePerTkm: 0.09,
      factoryWasteTreatmentKgCO2ePerDeclaredUnit: 0.25,
      siteWasteTransportDistanceKm: 35,
      siteWasteTransportKgCO2ePerTkm: 0.09,
      siteWasteTreatmentKgCO2ePerDeclaredUnit: 0.3,
    },
    {
      id: "membrane",
      name: "Breather membrane",
      boqQty: 120,
      boqUnit: "m2",
      conversionMode: "manual",
      conversionFactorToDeclaredUnit: 0.0,
      declaredUnit: "m2",
      factoryWasteRate: 0.03,
      siteWasteRate: 0.02,
      epdA1A3KgCO2ePerDeclaredUnit: 1.2,
      surfaceMassKgPerM2: 0.18,
      massTonnesPerDeclaredUnit: 0.0,
      inboundDistanceKm: 300,
      inboundTransportKgCO2ePerTkm: 0.09,
      factoryWasteTransportDistanceKm: 20,
      factoryWasteTransportKgCO2ePerTkm: 0.09,
      factoryWasteTreatmentKgCO2ePerDeclaredUnit: 0.08,
      siteWasteTransportDistanceKm: 35,
      siteWasteTransportKgCO2ePerTkm: 0.09,
      siteWasteTreatmentKgCO2ePerDeclaredUnit: 0.09,
    },
    {
      id: "steel-fixings",
      name: "Steel fixings and brackets",
      boqQty: 650,
      boqUnit: "kg",
      conversionMode: "manual",
      conversionFactorToDeclaredUnit: 0.0,
      declaredUnit: "kg",
      factoryWasteRate: 0.02,
      siteWasteRate: 0.01,
      epdA1A3KgCO2ePerDeclaredUnit: 2.4,
      massTonnesPerDeclaredUnit: 0.0,
      inboundDistanceKm: 260,
      inboundTransportKgCO2ePerTkm: 0.09,
      factoryWasteTransportDistanceKm: 25,
      factoryWasteTransportKgCO2ePerTkm: 0.09,
      factoryWasteTreatmentKgCO2ePerDeclaredUnit: 0.05,
      siteWasteTransportDistanceKm: 35,
      siteWasteTransportKgCO2ePerTkm: 0.09,
      siteWasteTreatmentKgCO2ePerDeclaredUnit: 0.04,
    },
  ],

  factory: {
  allocatedManufacturingKgCO2e: 850,
  a4DistanceKm: 160,
},

 

 

  endOfLife: {
    c1KgCO2e: 180,
    routes: [
      {
        id: "mixed-panel-eol",
        name: "Mixed panel waste route",
        massTonnes: 11.2,
        distanceKm: 55,
        transportKgCO2ePerTkm: 0.09,
        processingKgCO2ePerTonne: 14,
        disposedMassTonnes: 3.1,
        disposalKgCO2ePerTonne: 22,
      },
    ],
  },

 
};